//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accgame.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Acc()
        {
            this.Anh_Acc = new HashSet<Anh_Acc>();
            this.ApiAccs = new HashSet<ApiAcc>();
        }
    
        public int IDAcc { get; set; }
        public string TenAcc { get; set; }
        public string Server { get; set; }
        public string MaTaiKhoan { get; set; }
        public string ChiTiet { get; set; }
        public Nullable<int> Gia { get; set; }
        public Nullable<int> IDNguoiDung { get; set; }
        public Nullable<int> IDNguoiMua { get; set; }
        public Nullable<System.DateTime> ThoiGianDang { get; set; }
        public Nullable<System.DateTime> ThoiGianBan { get; set; }
        public Nullable<bool> DaBan { get; set; }
        public Nullable<bool> Xoa { get; set; }
        public string AnhDaiDien { get; set; }
        public string NhanVat { get; set; }
        public string VuKhi { get; set; }
        public Nullable<int> LoaiGame { get; set; }
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public string ThongTinKhac { get; set; }
        public string CapKhaiPha { get; set; }
        public Nullable<bool> TaiKhoanNoiBo { get; set; }
        public Nullable<bool> AccVip { get; set; }
        public Nullable<bool> AccKhoiDau { get; set; }
        public Nullable<bool> RanDom { get; set; }
        public string MaGiamGia { get; set; }
        public Nullable<int> SoTienGiam { get; set; }
        public string AnhNhanVat { get; set; }
        public string TenNhanVat { get; set; }
        public string AnhVuKhi { get; set; }
        public string TenVuKhi { get; set; }
        public Nullable<int> IDLoaiAcc { get; set; }
        public Nullable<int> IDOldAcc { get; set; }
        public Nullable<int> GiaCtvCollab { get; set; }
        public Nullable<int> GiaDaMua { get; set; }
        public Nullable<int> PhanTram { get; set; }
        public Nullable<int> GiaGoc { get; set; }
        public Nullable<bool> An { get; set; }
    
        public virtual LoaiAcc LoaiAcc { get; set; }
        public virtual LoaiGame LoaiGame1 { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NguoiDung NguoiDung1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anh_Acc> Anh_Acc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApiAcc> ApiAccs { get; set; }
    }
}
