//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accgame.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccRandom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AccRandom()
        {
            this.AccRandomDamuas = new HashSet<AccRandomDamua>();
        }
    
        public int IDAccRandom { get; set; }
        public Nullable<int> IDDanhMuc { get; set; }
        public string TaiKhoan { get; set; }
        public string MatKhau { get; set; }
        public string ThongTinKhac { get; set; }
        public Nullable<int> IDNguoiDung { get; set; }
        public Nullable<bool> Xoa { get; set; }
        public Nullable<bool> DaBan { get; set; }
        public Nullable<int> IDNguoiMua { get; set; }
        public Nullable<System.DateTime> ThoiGianBan { get; set; }
        public Nullable<int> IDOldAcc { get; set; }
        public Nullable<int> GiaDaMua { get; set; }
        public Nullable<System.DateTime> ThoiGianDang { get; set; }
        public string MatKhauOutlook { get; set; }
        public string MailKhoiPhuc { get; set; }
        public string MatKhauMailKhoiPhuc { get; set; }
        public string MatKhauMail { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NguoiDung NguoiDung1 { get; set; }
        public virtual DanhMuc DanhMuc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccRandomDamua> AccRandomDamuas { get; set; }
    }
}
