//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accgame.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccRandomDamua
    {
        public int ID { get; set; }
        public string Danhmuc { get; set; }
        public Nullable<int> IdAccRandom { get; set; }
        public string Server { get; set; }
        public string Ghichu { get; set; }
    
        public virtual AccRandom AccRandom { get; set; }
    }
}
