//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accgame.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminNotifyRead
    {
        public int IdStatusAdminNotify { get; set; }
        public Nullable<int> IdNotifyUser { get; set; }
        public Nullable<int> IdNguoidung { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NotifyUser NotifyUser { get; set; }
    }
}
