//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accgame.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminCongTien
    {
        public int IdAdminCongTien { get; set; }
        public Nullable<long> SoTien { get; set; }
        public Nullable<int> IDNguoiDung { get; set; }
        public Nullable<int> IDNguoiCong { get; set; }
        public string Lydo { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<bool> CongTien { get; set; }
        public Nullable<long> SoDuTruocCong { get; set; }
        public Nullable<long> SoDuSauCong { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> HuyDon { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NguoiDung NguoiDung1 { get; set; }
    }
}
