//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accgame.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnAcc
    {
        public int Id { get; set; }
        public Nullable<bool> AnAccVip { get; set; }
        public Nullable<bool> AnAccRR { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<bool> IsAdminAn { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
