//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accgame.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anh_Acc
    {
        public int IDAnh_Acc { get; set; }
        public string DuongDanAnh { get; set; }
        public Nullable<int> IDAcc { get; set; }
        public Nullable<int> IDNguoiDung { get; set; }
        public Nullable<bool> AnhDaiDien { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual Acc Acc { get; set; }
    }
}
