//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accgame.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class BienDongSoDu
    {
        public int IDBienDongSoDu { get; set; }
        public Nullable<long> SoTien { get; set; }
        public Nullable<bool> TruTien { get; set; }
        public Nullable<int> IDNguoiDung { get; set; }
        public string LoiNhan { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<long> TienTruoc { get; set; }
        public Nullable<long> TienSau { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
