//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accgame.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaiDat
    {
        public int IDCaiDat { get; set; }
        public string NoiDung { get; set; }
        public string MaCaiDat { get; set; }
        public Nullable<System.DateTime> ThoiGianHet { get; set; }
        public Nullable<System.DateTime> ThoiGianCapNhat { get; set; }
    }
}
