//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accgame.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaiDatVongQuay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CaiDatVongQuay()
        {
            this.VongQuays = new HashSet<VongQuay>();
        }
    
        public int IDCaiDatVongQuay { get; set; }
        public Nullable<double> TyLe1 { get; set; }
        public Nullable<double> TyLe2 { get; set; }
        public Nullable<double> TyLe3 { get; set; }
        public Nullable<double> TyLe4 { get; set; }
        public Nullable<double> TyLe5 { get; set; }
        public Nullable<double> TyLe6 { get; set; }
        public Nullable<int> Gia { get; set; }
        public Nullable<int> LoaiVong { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VongQuay> VongQuays { get; set; }
    }
}
