//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accgame.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class CayThue
    {
        public int IDCayThue { get; set; }
        public Nullable<int> IDNguoiDung { get; set; }
        public Nullable<int> IDGoiNhiemVu { get; set; }
        public Nullable<int> SoTien { get; set; }
        public string UID { get; set; }
        public string TenDangNhap { get; set; }
        public string MatKhau { get; set; }
        public string Server { get; set; }
        public string TenNhanVat { get; set; }
        public string SoDienThoai { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> HoanThanh { get; set; }
        public Nullable<System.DateTime> ThoiGianHoanThanh { get; set; }
        public Nullable<System.DateTime> ThoiGianGui { get; set; }
        public Nullable<int> LoaiGame { get; set; }
        public Nullable<int> IDNguoiNhan { get; set; }
    
        public virtual LoaiGame LoaiGame1 { get; set; }
        public virtual LoaiGame LoaiGame2 { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NguoiDung NguoiDung1 { get; set; }
        public virtual GoiNhiemVu GoiNhiemVu { get; set; }
    }
}
