//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accgame.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Code
    {
        public int IDCode { get; set; }
        public Nullable<int> GiaTri { get; set; }
        public Nullable<System.DateTime> ThoiGianMua { get; set; }
        public string MaCode { get; set; }
        public Nullable<int> IDLoaiCode { get; set; }
        public Nullable<int> IDNguoiDung { get; set; }
        public Nullable<bool> DaBan { get; set; }
        public Nullable<bool> Xoa { get; set; }
    
        public virtual LoaiCode LoaiCode { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
