//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accgame.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhMuc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DanhMuc()
        {
            this.AccRandoms = new HashSet<AccRandom>();
        }
    
        public int IDDanhMuc { get; set; }
        public Nullable<int> LoaiGame { get; set; }
        public string TenDanhMuc { get; set; }
        public string DanhMucLevel { get; set; }
        public string LuotRoll { get; set; }
        public Nullable<int> HienCo { get; set; }
        public Nullable<int> DaBan { get; set; }
        public Nullable<int> Gia { get; set; }
        public Nullable<bool> Xoa { get; set; }
        public string AnhDanhMuc { get; set; }
        public Nullable<bool> TaiKhoanNoiBo { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> STT { get; set; }
        public Nullable<int> IDNguoiDung { get; set; }
        public Nullable<bool> random { get; set; }
        public Nullable<int> IDLoaiAcc { get; set; }
        public string Server { get; set; }
        public string slug { get; set; }
        public Nullable<int> IDOldDanhMuc { get; set; }
        public string Ar { get; set; }
        public Nullable<int> GiaCtvCollab { get; set; }
        public string ThongBaoMuaAcc { get; set; }
        public string CauHinhDangNhieuAcc { get; set; }
        public string GhiChuAcc { get; set; }
        public Nullable<bool> Hide { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccRandom> AccRandoms { get; set; }
        public virtual LoaiAcc LoaiAcc { get; set; }
        public virtual LoaiGame LoaiGame1 { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
