//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accgame.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaiThuongVongQuay
    {
        public int IDGiaiThuongVongQuay { get; set; }
        public Nullable<bool> DaBan { get; set; }
        public string ThongTin { get; set; }
        public Nullable<System.DateTime> ThoiGianBan { get; set; }
        public Nullable<int> LoaiGiai { get; set; }
    }
}
