//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accgame.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoiNap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GoiNap()
        {
            this.NapGames = new HashSet<NapGame>();
        }
    
        public int IDGoiNap { get; set; }
        public Nullable<int> Gia { get; set; }
        public string TenGoi { get; set; }
        public Nullable<bool> Xoa { get; set; }
        public Nullable<int> SoThuTu { get; set; }
        public Nullable<int> LoaiGame { get; set; }
        public string Anh { get; set; }
        public Nullable<int> LoaiNap { get; set; }
        public string LinkHdUID { get; set; }
        public Nullable<bool> X2LanDau { get; set; }
        public Nullable<bool> An { get; set; }
        public Nullable<System.DateTime> ThoigianAn { get; set; }
    
        public virtual LoaiGame LoaiGame1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NapGame> NapGames { get; set; }
    }
}
