//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accgame.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoiNhiemVu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GoiNhiemVu()
        {
            this.CayThues = new HashSet<CayThue>();
        }
    
        public int IDGoiNhiemVu { get; set; }
        public string TenGoiNhiemVu { get; set; }
        public Nullable<int> GiaTien { get; set; }
        public Nullable<int> LoaiGame { get; set; }
        public Nullable<bool> Xoa { get; set; }
    
        public virtual LoaiGame LoaiGame1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CayThue> CayThues { get; set; }
    }
}
