//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accgame.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public int IDImage { get; set; }
        public Nullable<int> IDNguoiDung { get; set; }
        public string DuongDan { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
