//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accgame.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiAcc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiAcc()
        {
            this.Accs = new HashSet<Acc>();
            this.DanhMucs = new HashSet<DanhMuc>();
            this.LoaiAcc1 = new HashSet<LoaiAcc>();
        }
    
        public int IDLoaiAcc { get; set; }
        public string TenLoaiAcc { get; set; }
        public Nullable<int> DangBan { get; set; }
        public Nullable<int> DaBan { get; set; }
        public string Image { get; set; }
        public string slug { get; set; }
        public Nullable<bool> DacBiet { get; set; }
        public Nullable<int> IDLoaiGame { get; set; }
        public Nullable<int> STT { get; set; }
        public Nullable<bool> Hide { get; set; }
        public string MoTa { get; set; }
        public string Server { get; set; }
        public Nullable<int> IDLoaiAccCha { get; set; }
    
        public virtual LoaiGame LoaiGame { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acc> Accs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhMuc> DanhMucs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoaiAcc> LoaiAcc1 { get; set; }
        public virtual LoaiAcc LoaiAcc2 { get; set; }
    }
}
