//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accgame.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiGame
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiGame()
        {
            this.CayThues = new HashSet<CayThue>();
            this.CayThues1 = new HashSet<CayThue>();
            this.GoiNaps = new HashSet<GoiNap>();
            this.GoiNhiemVus = new HashSet<GoiNhiemVu>();
            this.LoaiAccs = new HashSet<LoaiAcc>();
            this.LoaiCodes = new HashSet<LoaiCode>();
            this.NhanVats = new HashSet<NhanVat>();
            this.VuKhis = new HashSet<VuKhi>();
            this.Accs = new HashSet<Acc>();
            this.DanhMucs = new HashSet<DanhMuc>();
        }
    
        public int IDLoaiGame { get; set; }
        public string TenLoaiGame { get; set; }
        public string Slug { get; set; }
        public string Image { get; set; }
        public Nullable<bool> Hide { get; set; }
        public Nullable<int> STT { get; set; }
        public string AnhNapGame { get; set; }
        public string AnhCayThue { get; set; }
        public Nullable<bool> DichVuCayThue { get; set; }
        public Nullable<bool> DichVuNapGame { get; set; }
        public Nullable<bool> DichVuCode { get; set; }
        public string AnhCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CayThue> CayThues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CayThue> CayThues1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoiNap> GoiNaps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoiNhiemVu> GoiNhiemVus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoaiAcc> LoaiAccs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LoaiCode> LoaiCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVat> NhanVats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VuKhi> VuKhis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acc> Accs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhMuc> DanhMucs { get; set; }
    }
}
