//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accgame.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiCode()
        {
            this.Codes = new HashSet<Code>();
        }
    
        public int IDLoaiCode { get; set; }
        public string TenLoaiCode { get; set; }
        public Nullable<int> Gia { get; set; }
        public Nullable<bool> Xoa { get; set; }
        public Nullable<bool> CodeNoiBo { get; set; }
        public Nullable<int> LoaiGame { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Code> Codes { get; set; }
        public virtual LoaiGame LoaiGame1 { get; set; }
    }
}
