//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accgame.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class accgameEntities : DbContext
    {
        public accgameEntities()
            : base("name=accgameEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccRandom> AccRandoms { get; set; }
        public virtual DbSet<Anh_Acc> Anh_Acc { get; set; }
        public virtual DbSet<ApiAcc> ApiAccs { get; set; }
        public virtual DbSet<Banner> Banners { get; set; }
        public virtual DbSet<BienDongSoDu> BienDongSoDus { get; set; }
        public virtual DbSet<CaiDat> CaiDats { get; set; }
        public virtual DbSet<CaiDatVongQuay> CaiDatVongQuays { get; set; }
        public virtual DbSet<CayThue> CayThues { get; set; }
        public virtual DbSet<Code> Codes { get; set; }
        public virtual DbSet<GiaiThuongVongQuay> GiaiThuongVongQuays { get; set; }
        public virtual DbSet<GoiNap> GoiNaps { get; set; }
        public virtual DbSet<GoiNhiemVu> GoiNhiemVus { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<LoaiAcc> LoaiAccs { get; set; }
        public virtual DbSet<LoaiCode> LoaiCodes { get; set; }
        public virtual DbSet<LoaiGame> LoaiGames { get; set; }
        public virtual DbSet<NapGame> NapGames { get; set; }
        public virtual DbSet<NapTien> NapTiens { get; set; }
        public virtual DbSet<NguoiDung> NguoiDungs { get; set; }
        public virtual DbSet<NhanVat> NhanVats { get; set; }
        public virtual DbSet<RutTien> RutTiens { get; set; }
        public virtual DbSet<SettingApi> SettingApis { get; set; }
        public virtual DbSet<Video> Videos { get; set; }
        public virtual DbSet<VongQuay> VongQuays { get; set; }
        public virtual DbSet<VuKhi> VuKhis { get; set; }
        public virtual DbSet<AdminCongTien> AdminCongTiens { get; set; }
        public virtual DbSet<Acc> Accs { get; set; }
        public virtual DbSet<DanhMuc> DanhMucs { get; set; }
        public virtual DbSet<OldPass> OldPasses { get; set; }
        public virtual DbSet<AccRandomDamua> AccRandomDamuas { get; set; }
        public virtual DbSet<AdminNotifyRead> AdminNotifyReads { get; set; }
        public virtual DbSet<NotifyUser> NotifyUsers { get; set; }
        public virtual DbSet<AnAcc> AnAccs { get; set; }
    }
}
