//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accgame.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class NapTien
    {
        public int IdNapTien { get; set; }
        public Nullable<int> IDNguoiDung { get; set; }
        public string Magd { get; set; }
        public string Noidung { get; set; }
        public Nullable<long> SoTien { get; set; }
        public Nullable<System.DateTime> thoigian { get; set; }
        public string request_id { get; set; }
        public string code { get; set; }
        public string serial { get; set; }
        public Nullable<int> amount { get; set; }
        public string telco { get; set; }
        public Nullable<bool> trangthai { get; set; }
        public Nullable<bool> atm { get; set; }
        public Nullable<long> TruocNap { get; set; }
        public Nullable<long> SauNap { get; set; }
        public Nullable<int> IDNguoiDuyet { get; set; }
    
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NguoiDung NguoiDung1 { get; set; }
    }
}
