//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accgame.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiDung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguoiDung()
        {
            this.AccRandoms = new HashSet<AccRandom>();
            this.AccRandoms1 = new HashSet<AccRandom>();
            this.Anh_Acc = new HashSet<Anh_Acc>();
            this.BienDongSoDus = new HashSet<BienDongSoDu>();
            this.CayThues = new HashSet<CayThue>();
            this.CayThues1 = new HashSet<CayThue>();
            this.Codes = new HashSet<Code>();
            this.Images = new HashSet<Image>();
            this.NapGames = new HashSet<NapGame>();
            this.NapTiens = new HashSet<NapTien>();
            this.RutTiens = new HashSet<RutTien>();
            this.VongQuays = new HashSet<VongQuay>();
            this.AdminCongTiens = new HashSet<AdminCongTien>();
            this.AdminCongTiens1 = new HashSet<AdminCongTien>();
            this.Accs = new HashSet<Acc>();
            this.Accs1 = new HashSet<Acc>();
            this.DanhMucs = new HashSet<DanhMuc>();
            this.NapGames1 = new HashSet<NapGame>();
            this.NapTiens1 = new HashSet<NapTien>();
            this.OldPasses = new HashSet<OldPass>();
            this.AdminNotifyReads = new HashSet<AdminNotifyRead>();
            this.NotifyUsers = new HashSet<NotifyUser>();
            this.NotifyUsers1 = new HashSet<NotifyUser>();
            this.AnAccs = new HashSet<AnAcc>();
            this.NapGames2 = new HashSet<NapGame>();
        }
    
        public int IDNguoiDung { get; set; }
        public string TenNguoiDung { get; set; }
        public string MatKhau { get; set; }
        public string Email { get; set; }
        public Nullable<long> Tien { get; set; }
        public Nullable<System.DateTime> NgayThamGia { get; set; }
        public Nullable<int> LeverAdmin { get; set; }
        public Nullable<int> MatMa { get; set; }
        public Nullable<int> ThoiVang { get; set; }
        public Nullable<int> TienNap { get; set; }
        public Nullable<int> HoaHong { get; set; }
        public Nullable<int> TienNapThang { get; set; }
        public Nullable<double> Phantramhoahong { get; set; }
        public string AnhDaiDien { get; set; }
        public string OldPass { get; set; }
        public Nullable<bool> OldAccount { get; set; }
        public Nullable<bool> GoogleAccount { get; set; }
        public Nullable<bool> CtvCollab { get; set; }
        public Nullable<bool> OnOffCtvCollab { get; set; }
        public string SessionID { get; set; }
        public string MatKhau2 { get; set; }
        public Nullable<int> FailedLoginAttempts { get; set; }
        public Nullable<System.DateTime> LockoutEndTime { get; set; }
        public Nullable<bool> Block { get; set; }
        public string BlockContent { get; set; }
        public string ResetPasswordToken { get; set; }
        public Nullable<System.DateTime> ResetTokenExpiry { get; set; }
        public string SessionID_Desktop { get; set; }
        public string SessionID_Mobile { get; set; }
        public Nullable<int> FailedPasswordRequests { get; set; }
        public Nullable<System.DateTime> LastPasswordRequestTime { get; set; }
        public Nullable<System.DateTime> LockedUntil { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccRandom> AccRandoms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccRandom> AccRandoms1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Anh_Acc> Anh_Acc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BienDongSoDu> BienDongSoDus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CayThue> CayThues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CayThue> CayThues1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Code> Codes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Image> Images { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NapGame> NapGames { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NapTien> NapTiens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RutTien> RutTiens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VongQuay> VongQuays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminCongTien> AdminCongTiens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminCongTien> AdminCongTiens1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acc> Accs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acc> Accs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhMuc> DanhMucs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NapGame> NapGames1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NapTien> NapTiens1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OldPass> OldPasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminNotifyRead> AdminNotifyReads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotifyUser> NotifyUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotifyUser> NotifyUsers1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnAcc> AnAccs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NapGame> NapGames2 { get; set; }
    }
}
