//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accgame.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVat
    {
        public int IDNhanVat { get; set; }
        public string TenNhanVat { get; set; }
        public Nullable<int> LoaiGame { get; set; }
        public string Avatar { get; set; }
        public Nullable<int> Sao { get; set; }
    
        public virtual LoaiGame LoaiGame1 { get; set; }
    }
}
