//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accgame.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotifyUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotifyUser()
        {
            this.AdminNotifyReads = new HashSet<AdminNotifyRead>();
        }
    
        public int IdNotify { get; set; }
        public string Contents { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<int> IdNguoidung { get; set; }
        public Nullable<bool> IsAdminPost { get; set; }
        public Nullable<int> IdAdmin { get; set; }
        public Nullable<System.DateTime> Thoigian { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminNotifyRead> AdminNotifyReads { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NguoiDung NguoiDung1 { get; set; }
    }
}
